name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ghcr-build-docker-images:
    name: ghcr-docker-build-${{ matrix.docker_image }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_image:
          - huginn/huginn
          - huginn/huginn-single-process
    env:
      DOCKER_IMAGE: ghcr.io/${{ matrix.docker_image }}
      DOCKERFILE: docker/${{ contains(matrix.docker_image, 'single-process') && 'single-process' || 'multi-process' }}/Dockerfile
      DOCKER_USER: ${{ github.actor }}
      DOCKER_PASS: ${{ secrets.GITHUB_TOKEN }}
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build a docker image
        run: |
            ./build_docker_image.sh --push
