name: Build and Push Multi-Platform Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .                      # Directorio raíz del repositorio
          file: ./docker/multi-process/Dockerfile       # Ruta específica del Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/huginn:latest
          platforms: linux/amd64,linux/arm64
